name: 'setup-cloudquery-action'
description: 'Setup CloudQuery CLI in a GitHub action environment'
author: CloudQuery
inputs:
  version:
    description: 'CloudQuery CLI version to install'
    default: 'latest'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
