name: setup-cloudquery example

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  cloudquery-sync:
    name: cloudquery-sync (${{ matrix.label }})
    permissions:
      id-token: write
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - label: "without-v-prefix"
            dbversion: "postgres:latest"
            cloudquery-version: "6.35.3"
            os: ubuntu-latest
          - label: "with-v-prefix"
            dbversion: "postgres:latest"
            cloudquery-version: "v6.35.4"
            os: ubuntu-latest
      fail-fast: false
    services:
      postgres:
        image: ${{ matrix.dbversion }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6
        with:
          role-to-assume: arn:aws:iam::615713231484:role/cq-playground-aws-github-action
          aws-region: us-east-1
      - name: Setup CloudQuery
        uses: ./.
        with:
          version: ${{matrix.cloudquery-version}}
      - name: Sync with CloudQuery
        env:
          CLOUDQUERY_API_KEY: ${{ secrets.CLOUDQUERY_API_KEY }}
        run: cloudquery sync example_configs/spec.yml --log-console
