name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@148653c6179832f8392d083de6b46ad3dcc54de3
        with:
          publish_latest_tag: true
          token: ${{ secrets.GITHUB_TOKEN }}
