name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const fn = require('./.github/scripts/update-major-tag.js');
            await fn({ github, context });
